---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nginx-deployment.yaml
configMapGenerator:
  - name: kustomize-config
    literals:
      - tag=1.1.19
replacements:
  - source:
      # Replace any matches by the value of environment variable `IMAGE_TAG`.
      kind: ConfigMap
      fieldPath: data.tag
    targets:
      - select:
          # In each Deployment resource …
          kind: Deployment
        fieldPaths:
          # … match the image of container `test-app` …
          - spec.template.spec.containers.[name=test-app].image
        options:
          # … but replace only the second part (image tag) when split by ":".
          delimiter: ":"
          index: 1